# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-case-conflict
          - id: mixed-line-ending
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: detect-private-key
          - id: no-commit-to-branch
            args: [--branch, master, --branch, develop]
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v15.0.7
      hooks:
          - id: clang-format
            types_or: [c++, c]
            args: ["-style=file"]
#-   repo: https://github.com/pocc/pre-commit-hooks
#    rev: v1.3.5
#    hooks:
#    -   id: clang-tidy
#        args: [-checks=clang-diagnostic-return-type]
#        files: src/.*\.cpp
